from __future__ import annotations

from typing import Optional, Literal

from pydantic import BaseModel, Field, EmailStr


class CandidateInvite(BaseModel):
    id: str
    companyId: str
    templateId: str
    candidateName: str
    candidateEmail: EmailStr
    status: str = "sent"
    token: str
    # interviewMode: 'ai' or 'rh' (human interviewer)
    interviewMode: Literal["ai", "rh"] = "ai"
    # optional candidate access credentials (generated by RH)
    candidateLogin: Optional[str] = None
    candidatePassword: Optional[str] = None
    createdAt: str
    updatedAt: Optional[str] = None


class CandidateInviteCreateRequest(BaseModel):
    templateId: str = Field(min_length=4)
    candidateName: str = Field(min_length=2)
    candidateEmail: EmailStr
    interviewMode: Literal["ai", "rh"] = "ai"
    generateCredentials: bool = False


class CandidateInviteListResponse(BaseModel):
    items: list[CandidateInvite] = Field(default_factory=list)
